* clj-ircbot
  A simple bot that consumes an IRC channel and stores it into Amazon SDB.

* Configuration
  The following system properties must be set either via -D java args or in a clj-ircbot.properties file locate don the classpath.

  aws.access-key => AWS access key
  aws.secret-key => AWS secret key
  ircbot.name => name for the bot (will become the NICK)
  ircbot.server => server to connect to (irc.freenode.net)
  ircbot.channel => channel to consume
  ircbot.channel-key => optional channel key if it is protected
  jetty.port => port number for the embedded HTTP server 

* License
  Copyright (c) Frank Failla. All rights reserved.
  The use and distribution terms for this software are covered by the
  Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
  which can be found in the file epl-v10.html at the root of this distribution.
  By using this software in any fashion, you are agreeing to be bound by
  the terms of this license.
  You must not remove this notice, or any other, from this software.

